apiVersion: apps/v1
kind: Deployment
metadata:
  name: "0x9"
  namespace: "0x9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "0x9"
  template:
    metadata:
      labels:
        app: "0x9"
    spec:
      containers:
      - name: "0x9"
        image: robbof/0x9
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "0x9"
  namespace: "0x9"
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: "0x9"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "0x9"
  namespace: "0x9"
spec:
  routes:
    - match: "Host(`0x9.uk`)"
      kind: Rule
      services:
      - kind: Service
        name: "0x9"
        namespace: "0x9"
        port: 80
  tls:
    certResolver: default
